services:
  db:
    image: postgres:18.1
    container_name: pull-request-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./migrations/0001_init.sql:/docker-entrypoint-initdb.d/0001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pull-request-service
    environment:
      DB_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: pull-request-service-swagger
    ports:
      - "7002:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    environment:
      - SWAGGER_JSON=/openapi.yaml
    depends_on:
      - app

  # Запускаются только при E2E тестах
  db_test:
    image: postgres:18.1
    container_name: pr-service-db-e2e
    environment:
      POSTGRES_DB: prtest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5440:5432" # Порт 5440
    volumes:
      - ./migrations/0001_init.sql:/docker-entrypoint-initdb.d/0001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d prtest"]
      interval: 2s
      timeout: 2s
      retries: 5

  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-service-app-e2e
    environment:
      DB_DSN: postgres://test:test@db_test:5432/prtest?sslmode=disable
    depends_on:
      db_test:
        condition: service_healthy
    ports:
      - "8090:8080"