services:
  db:
    image: postgres:18.1
    container_name: pull-request-service-db
    environment:
      POSTGRES_DB: prreviewer
      POSTGRES_USER: pruser
      POSTGRES_PASSWORD: prpassword
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/0001_init.sql:/docker-entrypoint-initdb.d/0001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pruser -d prreviewer"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pull-request-service
    environment:
      DB_DSN: postgres://pruser:prpassword@db:5432/prreviewer?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: pull-request-service-swagger
    ports:
      - "7002:8080"
    volumes:
      # Монтируем локальный openapi.yaml внутрь контейнера по пути /openapi.yaml
      - ./openapi.yaml:/openapi.yaml:ro
    environment:
      # Говорим swagger-ui, что спецификация лежит по пути /openapi.yaml
      - SWAGGER_JSON=/openapi.yaml
    depends_on:
      - app
